version: 2.1

jobs:
  build:
    docker:
      - image: docker/compose:1.29.2  # Sử dụng một hình ảnh Docker Compose cụ thể
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and test
          command: |
            docker-compose -f docker-compose.yml up -d --build
  deploy:
    docker:
      - image: docker/compose:1.29.2  # Sử dụng một hình ảnh Docker Compose cụ thể
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to production
          command: |
            docker-compose -f docker-compose.yml up -d --build
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # Thay thế bằng nhánh mà bạn muốn triển khai
      - deploy:
          filters:
            branches:
              only:
                - master  # Thay thế bằng nhánh mà bạn muốn triển khai
